---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind
from platform import python_version

print(np.version.version)
print(python_version())
print(pd.__version__)

1.11.3
3.6.7
0.19.2

# Assignment 4 - Hypothesis Testing
This assignment requires more individual learning than previous assignments - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

Definitions:
* A _quarter_ is a specific three month period, Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December.
* A _recession_ is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.
* A _recession bottom_ is the quarter within a recession which had the lowest GDP.
* A _university town_ is a city which has a high percentage of university students compared to the total population of the city.

**Hypothesis**: University towns have their mean housing prices less effected by recessions. Run a t-test to compare the ratio of the mean price of houses in university towns the quarter before the recession starts compared to the recession bottom. (`price_ratio=quarter_before_recession/recession_bottom`)

The following data files are available for this assignment:
* From the [Zillow research data site](http://www.zillow.com/research/data/) there is housing data for the United States. In particular the datafile for [all homes at a city level](http://files.zillowstatic.com/research/public/City/City_Zhvi_AllHomes.csv), ```City_Zhvi_AllHomes.csv```, has median home sale prices at a fine grained level.
* From the Wikipedia page on college towns is a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States) which has been copy and pasted into the file ```university_towns.txt```.
* From Bureau of Economic Analysis, US Department of Commerce, the [GDP over time](http://www.bea.gov/national/index.htm#gdp) of the United States in current dollars (use the chained value in 2009 dollars), in quarterly intervals, in the file ```gdplev.xls```. For this assignment, only look at GDP data from the first quarter of 2000 onward.

Each function in this assignment below is worth 10%, with the exception of ```run_ttest()```, which is worth 50%.

In [2]:
# Use this dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

In [28]:
def get_list_of_university_towns():
    '''Returns a DataFrame of towns and the states they are in from the 
    university_towns.txt list. The format of the DataFrame should be:
    DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], 
    columns=["State", "RegionName"]  )
    
    The following cleaning needs to be done:

    1. For "State", removing characters from "[" to the end.
    2. For "RegionName", when applicable, removing every character from " (" to the end.
    3. Depending on how you read the data, you may need to remove newline character '\n'. '''
    return "ANSWER"
import csv
university_states_and_towns = []
f = open('university_towns.txt', 'r')
reader = csv.reader(f)
for line in reader:
    if 'edit' in line[0]:
        state = line[0].split('[')[0]
    university_states_and_towns.append([state, line[0]])
university_states_and_towns
pd.DataFrame(university_states_and_towns)

                 0                                                  1
0          Alabama                                      Alabama[edit]
1          Alabama                      Auburn (Auburn University)[1]
2          Alabama             Florence (University of North Alabama)
3          Alabama    Jacksonville (Jacksonville State University)[2]
4          Alabama         Livingston (University of West Alabama)[2]
5          Alabama           Montevallo (University of Montevallo)[2]
6          Alabama                          Troy (Troy University)[2]
7          Alabama                  Tuscaloosa (University of Alabama
8          Alabama                  Tuskegee (Tuskegee University)[5]
9           Alaska                                       Alaska[edit]
10          Alaska      Fairbanks (University of Alaska Fairbanks)[2]
11         Arizona                                      Arizona[edit]
12         Arizona         Flagstaff (Northern Arizona University)[6]
13         Arizona                   Tempe (Arizona State University)
14         Arizona                     Tucson (University of Arizona)
15        Arkansas                                     Arkansas[edit]
16        Arkansas            Arkadelphia (Henderson State University
17        Arkansas                    Conway (Central Baptist College
18        Arkansas           Fayetteville (University of Arkansas)[7]
19        Arkansas           Jonesboro (Arkansas State University)[8]
20        Arkansas         Magnolia (Southern Arkansas University)[2]
21        Arkansas  Monticello (University of Arkansas at Monticel...
22        Arkansas         Russellville (Arkansas Tech University)[2]
23        Arkansas                     Searcy (Harding University)[5]
24      California                                   California[edit]
25      California                  Angwin (Pacific Union College)[2]
26      California              Arcata (Humboldt State University)[5]
27      California                 Berkeley (University of California
28      California                 Chico (California State University
29      California               Claremont (Claremont McKenna College
..             ...                                                ...
537     Washington          Cheney (Eastern Washington University)[2]
538     Washington      Ellensburg (Central Washington University)[5]
539     Washington           Pullman (Washington State University)[5]
540     Washington                                University District
541  West Virginia                                West Virginia[edit]
542  West Virginia                     Athens (Concord University)[2]
543  West Virginia     Buckhannon (West Virginia Wesleyan College)[2]
544  West Virginia            Fairmont (Fairmont State University)[2]
545  West Virginia             Glenville (Glenville State College)[2]
546  West Virginia                Huntington (Marshall University)[2]
547  West Virginia  Montgomery (West Virginia University Institute...
548  West Virginia           Morgantown (West Virginia University)[2]
549  West Virginia             Shepherdstown (Shepherd University)[2]
550  West Virginia          West Liberty (West Liberty University)[2]
551      Wisconsin                                    Wisconsin[edit]
552      Wisconsin                     Appleton (Lawrence University)
553      Wisconsin    Eau Claire (University of Wisconsin–Eau Claire)
554      Wisconsin      Green Bay (University of Wisconsin-Green Bay)
555      Wisconsin       La Crosse (University of Wisconsin–La Crosse
556      Wisconsin       Madison (University of Wisconsin–Madison)[2]
557      Wisconsin       Menomonie (University of Wisconsin–Stout)[2]
558      Wisconsin                    Milwaukee (Marquette University
559      Wisconsin          Oshkosh (University of Wisconsin–Oshkosh)
560      Wisconsin  Platteville (University of Wisconsin–Plattevil...
561      Wisconsin  River Falls (University of Wisconsin–River Fal...
562      Wisconsin  Stevens Point (University of Wisconsin–Stevens...
563      Wisconsin                      Waukesha (Carroll University)
564      Wisconsin  Whitewater (University of Wisconsin–Whitewater...
565        Wyoming                                      Wyoming[edit]
566        Wyoming                 Laramie (University of Wyoming)[5]

[567 rows x 2 columns]

In [ ]:
def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3'''
    
    return "ANSWER"

In [ ]:
def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''
       
    return "ANSWER"

In [ ]:
def get_recession_bottom():
    '''Returns the year and quarter of the recession bottom time as a 
    string value in a format such as 2005q3'''
    
    return "ANSWER"

In [ ]:
def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].
    
    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.
    
    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''
    
    return "ANSWER"

In [ ]:
def run_ttest():
    '''First creates new data showing the decline or growth of housing prices
    between the recession start and the recession bottom. Then runs a ttest
    comparing the university town values to the non-university towns values, 
    return whether the alternative hypothesis (that the two groups are the same)
    is true or not as well as the p-value of the confidence. 
    
    Return the tuple (different, p, better) where different=True if the t-test is
    True at a p<0.01 (we reject the null hypothesis), or different=False if 
    otherwise (we cannot reject the null hypothesis). The variable p should
    be equal to the exact p value returned from scipy.stats.ttest_ind(). The
    value for better should be either "university town" or "non-university town"
    depending on which has a lower mean price ratio (which is equivilent to a
    reduced market loss).'''
    
    return "ANSWER"