# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [2]:
import pandas as pd
import numpy as np

In [177]:
energy = pd.read_excel('Energy Indicators.xls', skiprows=17, skipfooter=38)
energy

In [178]:
test = energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'])
# test

In [179]:
test = test.rename(columns={'Unnamed: 2': 'Country', 'Petajoules': 'Energy Supply', 'Gigajoules': 'Energy Supply per Capita', '%': '% Renewable'})
# test

In [180]:
test.head()

          Country Energy Supply Energy Supply per Capita  % Renewable
0     Afghanistan           321                       10    78.669280
1         Albania           102                       35   100.000000
2         Algeria          1959                       51     0.551010
3  American Samoa           ...                      ...     0.641026
4         Andorra             9                      121    88.695650

In [181]:
test = test.applymap(lambda x: np.NAN if(x == '...') else x)

In [182]:
test['Energy Supply'] *= 1000000
test

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
5,Angola,6.420000e+08,27.0,70.909090
6,Anguilla,2.000000e+06,136.0,0.000000
7,Antigua and Barbuda,8.000000e+06,84.0,0.000000
8,Argentina,3.378000e+09,79.0,24.064520
9,Armenia,1.430000e+08,48.0,28.236060
10,Aruba,1.200000e+07,120.0,14.870690
11,Australia1,5.386000e+09,231.0,11.810810
12,Austria,1.391000e+09,164.0,72.452820
13,Azerbaijan,5.670000e+08,60.0,6.384345
14,Bahamas,4.500000e+07,118.0,0.000000
15,Bahrain,5.740000e+08,425.0,0.000000
16,Bangladesh,1.625000e+09,10.0,1.966329
17,Barbados,1.900000e+07,69.0,0.000000
18,Belarus,1.142000e+09,120.0,0.463389
19,Belgium,2.338000e+09,210.0,9.959739
20,Belize,1.300000e+07,39.0,64.690030
21,Benin,1.700000e+08,16.0,0.000000
22,Bermuda,6.000000e+06,88.0,0.000000
23,Bhutan,6.300000e+07,83.0,100.000000
24,Bolivia (Plurinational State of),3.360000e+08,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0.000000
26,Bosnia and Herzegovina,2.660000e+08,70.0,41.464670
27,Botswana,8.600000e+07,39.0,0.131406
28,Brazil,1.214900e+10,59.0,69.648030
29,British Virgin Islands,2.000000e+06,85.0,0.000000
...,...,...,...,...
197,Switzerland17,1.113000e+09,136.0,57.745480
198,Syrian Arab Republic,5.420000e+08,28.0,11.568270
199,Tajikistan,1.060000e+08,13.0,99.742920
200,Thailand,5.336000e+09,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,1.170000e+08,56.0,26.140470
202,Timor-Leste,7.000000e+06,6.0,0.000000
203,Togo,1.340000e+08,19.0,80.180180
204,Tonga,3.000000e+06,28.0,0.000000
205,Trinidad and Tobago,8.240000e+08,611.0,0.000000
206,Tunisia,4.300000e+08,39.0,3.492547
207,Turkey,4.897000e+09,64.0,28.536690
208,Turkmenistan,1.102000e+09,210.0,0.000000
209,Turks and Caicos Islands,3.000000e+06,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,4.520000e+08,12.0,68.018180
212,Ukraine18,4.844000e+09,107.0,8.067312
213,United Arab Emirates,2.710000e+09,300.0,0.000000
214,United Kingdom of Great Britain and Northern I...,7.920000e+09,124.0,10.600470
215,United Republic of Tanzania,9.940000e+08,20.0,31.072840
216,United States of America20,9.083800e+10,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,1.960000e+08,58.0,71.605040
219,Uzbekistan,1.798000e+09,62.0,21.328410
220,Vanuatu,3.000000e+06,10.0,14.705880
221,Venezuela (Bolivarian Republic of),2.871000e+09,95.0,67.834520
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120

In [183]:
res = test.copy()
res.head()

          Country  Energy Supply  Energy Supply per Capita  % Renewable
0     Afghanistan   3.210000e+08                      10.0    78.669280
1         Albania   1.020000e+08                      35.0   100.000000
2         Algeria   1.959000e+09                      51.0     0.551010
3  American Samoa            NaN                       NaN     0.641026
4         Andorra   9.000000e+06                     121.0    88.695650

In [184]:
def clean_name(item):
    if '(' in item:
        item = item.split('(')[0]
    cleaned = [i for i in item if not i.isdigit()]
    return ''.join(cleaned)
res['Country'] = res['Country'].apply(clean_name)
res

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
5,Angola,6.420000e+08,27.0,70.909090
6,Anguilla,2.000000e+06,136.0,0.000000
7,Antigua and Barbuda,8.000000e+06,84.0,0.000000
8,Argentina,3.378000e+09,79.0,24.064520
9,Armenia,1.430000e+08,48.0,28.236060
10,Aruba,1.200000e+07,120.0,14.870690
11,Australia,5.386000e+09,231.0,11.810810
12,Austria,1.391000e+09,164.0,72.452820
13,Azerbaijan,5.670000e+08,60.0,6.384345
14,Bahamas,4.500000e+07,118.0,0.000000
15,Bahrain,5.740000e+08,425.0,0.000000
16,Bangladesh,1.625000e+09,10.0,1.966329
17,Barbados,1.900000e+07,69.0,0.000000
18,Belarus,1.142000e+09,120.0,0.463389
19,Belgium,2.338000e+09,210.0,9.959739
20,Belize,1.300000e+07,39.0,64.690030
21,Benin,1.700000e+08,16.0,0.000000
22,Bermuda,6.000000e+06,88.0,0.000000
23,Bhutan,6.300000e+07,83.0,100.000000
24,Bolivia,3.360000e+08,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0.000000
26,Bosnia and Herzegovina,2.660000e+08,70.0,41.464670
27,Botswana,8.600000e+07,39.0,0.131406
28,Brazil,1.214900e+10,59.0,69.648030
29,British Virgin Islands,2.000000e+06,85.0,0.000000
...,...,...,...,...
197,Switzerland,1.113000e+09,136.0,57.745480
198,Syrian Arab Republic,5.420000e+08,28.0,11.568270
199,Tajikistan,1.060000e+08,13.0,99.742920
200,Thailand,5.336000e+09,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,1.170000e+08,56.0,26.140470
202,Timor-Leste,7.000000e+06,6.0,0.000000
203,Togo,1.340000e+08,19.0,80.180180
204,Tonga,3.000000e+06,28.0,0.000000
205,Trinidad and Tobago,8.240000e+08,611.0,0.000000
206,Tunisia,4.300000e+08,39.0,3.492547
207,Turkey,4.897000e+09,64.0,28.536690
208,Turkmenistan,1.102000e+09,210.0,0.000000
209,Turks and Caicos Islands,3.000000e+06,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,4.520000e+08,12.0,68.018180
212,Ukraine,4.844000e+09,107.0,8.067312
213,United Arab Emirates,2.710000e+09,300.0,0.000000
214,United Kingdom of Great Britain and Northern I...,7.920000e+09,124.0,10.600470
215,United Republic of Tanzania,9.940000e+08,20.0,31.072840
216,United States of America,9.083800e+10,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,1.960000e+08,58.0,71.605040
219,Uzbekistan,1.798000e+09,62.0,21.328410
220,Vanuatu,3.000000e+06,10.0,14.705880
221,Venezuela,2.871000e+09,95.0,67.834520
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120

In [185]:
old_names = ['Republic of Korea', 'United States of America', 'United Kingdom of Great Britain and Northern Ireland', 'China, Hong Kong Special Administrative Region']
new_names = ['South Korea', 'United States', 'United Kingdom', 'Hong Kong']

res = res.replace(old_names, new_names)
res

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
5,Angola,6.420000e+08,27.0,70.909090
6,Anguilla,2.000000e+06,136.0,0.000000
7,Antigua and Barbuda,8.000000e+06,84.0,0.000000
8,Argentina,3.378000e+09,79.0,24.064520
9,Armenia,1.430000e+08,48.0,28.236060
10,Aruba,1.200000e+07,120.0,14.870690
11,Australia,5.386000e+09,231.0,11.810810
12,Austria,1.391000e+09,164.0,72.452820
13,Azerbaijan,5.670000e+08,60.0,6.384345
14,Bahamas,4.500000e+07,118.0,0.000000
15,Bahrain,5.740000e+08,425.0,0.000000
16,Bangladesh,1.625000e+09,10.0,1.966329
17,Barbados,1.900000e+07,69.0,0.000000
18,Belarus,1.142000e+09,120.0,0.463389
19,Belgium,2.338000e+09,210.0,9.959739
20,Belize,1.300000e+07,39.0,64.690030
21,Benin,1.700000e+08,16.0,0.000000
22,Bermuda,6.000000e+06,88.0,0.000000
23,Bhutan,6.300000e+07,83.0,100.000000
24,Bolivia,3.360000e+08,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0.000000
26,Bosnia and Herzegovina,2.660000e+08,70.0,41.464670
27,Botswana,8.600000e+07,39.0,0.131406
28,Brazil,1.214900e+10,59.0,69.648030
29,British Virgin Islands,2.000000e+06,85.0,0.000000
...,...,...,...,...
197,Switzerland,1.113000e+09,136.0,57.745480
198,Syrian Arab Republic,5.420000e+08,28.0,11.568270
199,Tajikistan,1.060000e+08,13.0,99.742920
200,Thailand,5.336000e+09,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,1.170000e+08,56.0,26.140470
202,Timor-Leste,7.000000e+06,6.0,0.000000
203,Togo,1.340000e+08,19.0,80.180180
204,Tonga,3.000000e+06,28.0,0.000000
205,Trinidad and Tobago,8.240000e+08,611.0,0.000000
206,Tunisia,4.300000e+08,39.0,3.492547
207,Turkey,4.897000e+09,64.0,28.536690
208,Turkmenistan,1.102000e+09,210.0,0.000000
209,Turks and Caicos Islands,3.000000e+06,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,4.520000e+08,12.0,68.018180
212,Ukraine,4.844000e+09,107.0,8.067312
213,United Arab Emirates,2.710000e+09,300.0,0.000000
214,United Kingdom,7.920000e+09,124.0,10.600470
215,United Republic of Tanzania,9.940000e+08,20.0,31.072840
216,United States,9.083800e+10,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,1.960000e+08,58.0,71.605040
219,Uzbekistan,1.798000e+09,62.0,21.328410
220,Vanuatu,3.000000e+06,10.0,14.705880
221,Venezuela,2.871000e+09,95.0,67.834520
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120

In [194]:
energy = pd.read_excel('Energy Indicators.xls', skiprows=17, skipfooter=38)
energy = (energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'])
                .rename(columns={'Unnamed: 2': 'Country', 'Petajoules': 'Energy Supply', 'Gigajoules': 'Energy Supply per Capita', '%': '% Renewable'})
                .applymap(lambda x: np.NAN if(x == '...') else x)
         )
energy['Energy Supply'] *= 1000000

# Function to clean name
def clean_name(item):
    if '(' in item:
        item = item.split('(')[0]
    cleaned = [i for i in item if not i.isdigit()]
    return ''.join(cleaned)

energy['Country'] = energy['Country'].apply(clean_name)

# Replace names
old_names = ['Republic of Korea', 'United States of America', 'United Kingdom of Great Britain and Northern Ireland', 'China, Hong Kong Special Administrative Region']
new_names = ['South Korea', 'United States', 'United Kingdom', 'Hong Kong']

energy = energy.replace(old_names, new_names)

energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
5,Angola,6.420000e+08,27.0,70.909090
6,Anguilla,2.000000e+06,136.0,0.000000
7,Antigua and Barbuda,8.000000e+06,84.0,0.000000
8,Argentina,3.378000e+09,79.0,24.064520
9,Armenia,1.430000e+08,48.0,28.236060
10,Aruba,1.200000e+07,120.0,14.870690
11,Australia,5.386000e+09,231.0,11.810810
12,Austria,1.391000e+09,164.0,72.452820
13,Azerbaijan,5.670000e+08,60.0,6.384345
14,Bahamas,4.500000e+07,118.0,0.000000
15,Bahrain,5.740000e+08,425.0,0.000000
16,Bangladesh,1.625000e+09,10.0,1.966329
17,Barbados,1.900000e+07,69.0,0.000000
18,Belarus,1.142000e+09,120.0,0.463389
19,Belgium,2.338000e+09,210.0,9.959739
20,Belize,1.300000e+07,39.0,64.690030
21,Benin,1.700000e+08,16.0,0.000000
22,Bermuda,6.000000e+06,88.0,0.000000
23,Bhutan,6.300000e+07,83.0,100.000000
24,Bolivia,3.360000e+08,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0.000000
26,Bosnia and Herzegovina,2.660000e+08,70.0,41.464670
27,Botswana,8.600000e+07,39.0,0.131406
28,Brazil,1.214900e+10,59.0,69.648030
29,British Virgin Islands,2.000000e+06,85.0,0.000000
...,...,...,...,...
197,Switzerland,1.113000e+09,136.0,57.745480
198,Syrian Arab Republic,5.420000e+08,28.0,11.568270
199,Tajikistan,1.060000e+08,13.0,99.742920
200,Thailand,5.336000e+09,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,1.170000e+08,56.0,26.140470
202,Timor-Leste,7.000000e+06,6.0,0.000000
203,Togo,1.340000e+08,19.0,80.180180
204,Tonga,3.000000e+06,28.0,0.000000
205,Trinidad and Tobago,8.240000e+08,611.0,0.000000
206,Tunisia,4.300000e+08,39.0,3.492547
207,Turkey,4.897000e+09,64.0,28.536690
208,Turkmenistan,1.102000e+09,210.0,0.000000
209,Turks and Caicos Islands,3.000000e+06,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,4.520000e+08,12.0,68.018180
212,Ukraine,4.844000e+09,107.0,8.067312
213,United Arab Emirates,2.710000e+09,300.0,0.000000
214,United Kingdom,7.920000e+09,124.0,10.600470
215,United Republic of Tanzania,9.940000e+08,20.0,31.072840
216,United States,9.083800e+10,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,1.960000e+08,58.0,71.605040
219,Uzbekistan,1.798000e+09,62.0,21.328410
220,Vanuatu,3.000000e+06,10.0,14.705880
221,Venezuela,2.871000e+09,95.0,67.834520
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120

In [236]:
GDP = pd.read_csv('world_bank.csv', skiprows=4)
edit_names = {
    "Korea, Rep.": "South Korea", 
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
}

GDP = GDP.rename(columns={'Country Name': 'Country'})
GDP.replace({'Country': edit_names}, inplace=True)
GDP = GDP.set_index('Country')
last_10_years = [i for i in GDP.columns if i.isdigit() and int(i) > 2005]
GDP = GDP[last_10_years]
GDP

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
Andorra,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
Afghanistan,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Angola,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
Albania,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
Arab World,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
United Arab Emirates,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
Argentina,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
Armenia,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
Australia,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Austria,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
Azerbaijan,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
Burundi,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
Belgium,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
Benin,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
Burkina Faso,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
Bangladesh,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
Bulgaria,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
Bahrain,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
"Bahamas, The",8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
Bosnia and Herzegovina,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
Belarus,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
Belize,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
Bermuda,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
Bolivia,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
Brazil,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
Barbados,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
Brunei Darussalam,1.249730e+10,1.251661e+10,1.227383e+10,1.205725e+10,1.237062e+10,1.279491e+10,1.291625e+10,1.268996e+10,1.239301e+10,1.233105e+10
...,...,...,...,...,...,...,...,...,...,...
Middle East & North Africa (IDA & IBRD countries),1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
Timor-Leste,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
Tonga,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
South Asia (IDA & IBRD),1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
Sub-Saharan Africa (IDA & IBRD countries),1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
Trinidad and Tobago,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
Tunisia,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
Turkey,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
Tuvalu,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
Tanzania,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
Uganda,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
Ukraine,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
Upper middle income,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
Uruguay,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
United States,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Uzbekistan,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
St. Vincent and the Grenadines,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
"Venezuela, RB",3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vietnam,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
Vanuatu,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
West Bank and Gaza,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
World,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
Samoa,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
"Yemen, Rep.",2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
South Africa,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
"Congo, Dem. Rep.",1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
Zambia,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [260]:
ScimEn = pd.read_excel('scimagojr-3.xlsx')
# ScimEn = ScimEn[(ScimEn['Rank'] <= 15)]
# ScimEn

In [261]:
ans = pd.merge(pd.merge(ScimEn, energy, how='outer', left_on='Country', right_on='Country'), GDP, left_on='Country', right_index=True)
ans = ans.set_index('Country')
ans = ans[ans['Rank'] <= 15]
ans

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,NaN,NaN,NaN,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [259]:
ans.shape

(15, 20)

In [466]:
# -----------Energy DF-----------
energy = pd.read_excel('Energy Indicators.xls', skiprows=17, skipfooter=38)
energy = (energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'])
                .rename(columns={'Unnamed: 2': 'Country', 'Petajoules': 'Energy Supply', 'Gigajoules': 'Energy Supply per Capita', '%': '% Renewable'})
                .applymap(lambda x: np.NAN if(x == '...') else x)
         )
energy['Energy Supply'] *= 1000000

# Function to clean name
def clean_name(item):
    if '(' in item:
        item = item.split('(')[0]
    cleaned = [i for i in item if not i.isdigit()]
    return ''.join(cleaned)

energy['Country'] = energy['Country'].apply(clean_name)

# Replace names
old_names = ['Republic of Korea', 'United States of America', 'United Kingdom of Great Britain and Northern Ireland', 'China, Hong Kong Special Administrative Region']
new_names = ['South Korea', 'United States', 'United Kingdom', 'Hong Kong']

energy = energy.replace(old_names, new_names)

# -----------GDP DF-----------
GDP = pd.read_csv('world_bank.csv', skiprows=4)
edit_names = {
    "Korea, Rep.": "South Korea", 
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
}

GDP = GDP.rename(columns={'Country Name': 'Country'})
GDP.replace({'Country': edit_names}, inplace=True)
GDP = GDP.set_index('Country')
last_10_years = [i for i in GDP.columns if i.isdigit() and int(i) > 2005]
GDP = GDP[last_10_years]

# ----------ScimEn DF-----------
ScimEn = pd.read_excel('scimagojr-3.xlsx')

# -----------Merge the DFs-----------
ans = pd.merge(pd.merge(ScimEn, energy, how='outer', left_on='Country', right_on='Country'), GDP, left_on='Country', right_index=True)
ans = ans.set_index('Country')
ans = ans[ans['Rank'] <= 15]
ans

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,NaN,NaN,NaN,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [263]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [268]:
everything = pd.merge(pd.merge(ScimEn, energy, how='outer', left_on='Country', right_on='Country'), GDP, how='outer', left_on='Country', right_index=True)
common = pd.merge(pd.merge(ScimEn, energy, how='inner', left_on='Country', right_on='Country'), GDP, how='inner', left_on='Country', right_index=True)
len(everything) - len(common)

161

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [465]:
Top15 = ans.copy()
params = [i for i in Top15.columns if i.isdigit()]
test = ans[params]
avgGDP = test.mean(axis=1).sort_values(ascending=False)
avgGDP

Country
China    6.348609e+12
dtype: float64

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [451]:
test = Top15.copy()
params = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
avg_GDP = Top15[params].mean(axis=1)
test['avgGDP'] = avg_GDP
sixth_largest_GDP = test[test['avgGDP'] == avg_GDP.sort_values(ascending=False)[5]].index[0]
test.loc[sixth_largest_GDP, '2015'] - test.loc[sixth_largest_GDP, '2006']

IndexError: index out of bounds

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [452]:
test = Top15.copy()
test['Energy Supply per Capita'].mean()

93.0

In [453]:
test = Top15.copy()
rrr = test['Energy Supply per Capita'].mean(axis=0, skipna=False)
type(float(rrr))

float

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [454]:
ans = test[test['% Renewable'] == max(test['% Renewable'])]
(ans.index[0], ans['% Renewable'])

('China', Country
 China    19.75491
 Name: % Renewable, dtype: float64)

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [455]:
test['new_ratio'] = test['Self-citations']/test['Citations']
ans = test[test['new_ratio'] == max(test['new_ratio'])]
(ans.index[0], ans['new_ratio'])

('China', Country
 China    0.689313
 Name: new_ratio, dtype: float64)

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [456]:
test['est_pop'] = test['Energy Supply']/test['Energy Supply per Capita']
pop = test['est_pop'].sort_values(ascending=False)
res = test[test['est_pop'] == pop[2]].index[0]
res

IndexError: index out of bounds

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [457]:
test['cit_docs_pp'] = test['Citable documents']/test['est_pop']
test['cit_docs_pp'].corr(test['Energy Supply per Capita'])

/home/mohit/.local/share/virtualenvs/coursera_datasci-baD6yU-8/lib/python3.6/site-packages/numpy/lib/function_base.py:2392: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/home/mohit/.local/share/virtualenvs/coursera_datasci-baD6yU-8/lib/python3.6/site-packages/numpy/lib/function_base.py:2326: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

nan

In [458]:
test['cit_docs_pp'] = test['Citable documents']/(test['Energy Supply']/test['Energy Supply per Capita'])
test['cit_docs_pp'].corr(test['Energy Supply per Capita'])

nan

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [459]:
median_prv = test['% Renewable'].median()
test['HighRenew'] = test['% Renewable'] >= median_prv
test = test.replace([True, False], [1,0])
test['HighRenew']

Country
China    1
Name: HighRenew, dtype: int64

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [467]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

In [468]:
groups = pd.DataFrame(columns = ['size', 'sum', 'mean', 'std'])
groups

Empty DataFrame
Columns: [size, sum, mean, std]
Index: []

In [469]:
Top15 = ans.copy()
Top15['Estimate Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
Top15

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Estimate Population
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.754910,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.570980,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,3.176154e+08
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.232820,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.274094e+08
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.600470,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,6.387097e+07
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.288680,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.435000e+08
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.945430,...,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,3.523986e+07
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.901530,...,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,8.036970e+07
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.969080,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.020280,...,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,6.383735e+07
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.279353,...,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,4.980543e+07
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.667230,...,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,5.990826e+07
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.968590,...,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,4.644340e+07
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,NaN,NaN,NaN,...,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.810810,...,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,2.331602e+07
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648030,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.059153e+08

In [474]:
for group, frame in Top15.groupby(ContinentDict):
    groups.loc[group] = [len(frame), frame['Estimate Population'].sum(),frame['Estimate Population'].mean(),frame['Estimate Population'].std()]
groups

               size           sum          mean           std
Asia            5.0  2.821591e+09  7.053977e+08  7.138779e+08
Australia       1.0  2.331602e+07  2.331602e+07           NaN
Europe          6.0  4.579297e+08  7.632161e+07  3.464767e+07
North America   2.0  3.528552e+08  1.764276e+08  1.996696e+08
South America   1.0  2.059153e+08  2.059153e+08           NaN

In [475]:
Top15 = ans.copy()
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

group_structure = pd.DataFrame(columns = ['size', 'sum', 'mean', 'std'])

Top15['Estimate Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
for group, frame in Top15.groupby(ContinentDict):
    groups.loc[group] = [len(frame), frame['Estimate Population'].sum(),frame['Estimate Population'].mean(),frame['Estimate Population'].std()]
groups

               size           sum          mean           std
Asia            5.0  2.821591e+09  7.053977e+08  7.138779e+08
Australia       1.0  2.331602e+07  2.331602e+07           NaN
Europe          6.0  4.579297e+08  7.632161e+07  3.464767e+07
North America   2.0  3.528552e+08  1.764276e+08  1.996696e+08
South America   1.0  2.059153e+08  2.059153e+08           NaN

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [492]:
t = Top15.copy()
cc = pd.cut(t['% Renewable'], 5)
for g, f in t.groupby([ContinentDict, cc]):
#     print(dir(g))
    print(len(g))

2
2
2
2
2
2
2
2
2

In [494]:
    q = Top15.copy()
    q = q.reset_index()
    q['Continent'] = [ContinentDict[country] for country in q['Country']]
    q['bins'] = pd.cut(q['% Renewable'],5)
    q.groupby(['Continent','bins']).size()

Continent      bins
Asia           (2.212, 15.753]     3
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

In [495]:
fin = ans.copy()

In [501]:
fin['Population Estimate'] = fin['Energy Supply']/fin['Energy Supply per Capita']
fin['PopEst'] = fin['Population Estimate'].apply(lambda x: "{:,}".format(x))
fin['PopEst']

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                                    nan
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: PopEst, dtype: object